### ISSUE TITLE
Need image for raspberry pi zero 2w

### ISSUE THREAD

**Issue by dharmeshmp** [TOLDOTECHNIK/Raspberry-Pi-Video-Looper#1]
Hi,

Your pre-compiled images are not working in pi zero 2w. 
Can you please create it for pi zero 2w?

**Comment by TOLDOTECHNIK** [comment]
We will try to build the image for the Raspberry Pi Zero 2 W tomorrow...

**Comment by TOLDOTECHNIK** [comment]
We got the image to compile but the system does not boot properly. We would have to invest more time, which is not possible at the moment.

**Comment by dharmeshmp** [comment]
Hi @TOLDOTECHNIK 

Thanks for your effort.

**Comment by dharmeshmp** [comment]
I managed to create image for zero 2w my self.

**Comment by TOLDOTECHNIK** [comment]
Can you please provide the changes you made, so we can update this project accordingly?

**Comment by dharmeshmp** [comment]
Actually i applied changes in fresh buildroot project with latest branch. 
Let me know, If you you want then I will provide config file.

**Comment by TOLDOTECHNIK** [comment]
Can you please send us your config file. Then we will try to implement it. Thanks
